### ISSUE TITLE
Is this only available for Windows?

### ISSUE THREAD

**Issue by navio** [r15ch13/audible-converter#1]

**Comment by r15ch13** [comment]
You can use it on Linux and MacOS if you know the activation bytes. I didn't implement a function to get them on other systems than windows. Please try the [audible-activator](https://github.com/inAudible-NG/audible-activator)

**Comment by TigerWolf** [comment]
The `regedit` npm module requires windows.

**Comment by r15ch13** [comment]
Should be fixed with e1d9666
