### ISSUE TITLE
Add link for getting activation bytes on non-Windows systems

### ISSUE THREAD

**Issue by r89m** [r15ch13/audible-converter#2]
Thanks for this great tool - I can now stream my audio books via Sonos!

One issue I had was trying to work out where to find the activation bytes as I was using your module on OSX. Would you consider adding a link to audible-activator or this stackoverflow question: http://apple.stackexchange.com/a/243670 to the README. Would have saved a little confusion at the beginning.

Thanks again,

Richard

**Comment by r15ch13** [comment]
Thanks, added the link to the readme.
