### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by pierrenel** [r15ch13/audible-converter#5]
Currently using node v8.1.0 via nvm, getting:

`env: node\r: No such file or directory`

when running audible-converter on OSX Sierra

**Comment by r15ch13** [comment]
Does `node -v` show you the version? Did you try restarting the terminal?

**Comment by pierrenel** [comment]
`16:04/0 iMac:~ pierre$  ~ $ node -v
v8.1.0`

Yep, restarted a new Terminal, incase the paths were weird.

**Comment by r15ch13** [comment]
Just to add one more project to the issue: https://github.com/nwjs-community/nw-builder/issues/75
Didn't find a solution in those issues yet 😄

**Comment by r15ch13** [comment]
Ah I found it ... at some point [bin/audible-converter](https://github.com/r15ch13/audible-converter/blob/master/bin/audible-converter) had crlf line endings and I published it...

**Comment by r15ch13** [comment]
Should be fixed with version 1.2.0 which I just published 👍

**Comment by pierrenel** [comment]
holy moly, it's working! thank you!

**Comment by r15ch13** [comment]
And it has new features! 😁
