### ISSUE TITLE
mac binary for rcrack?

### ISSUE THREAD

**Issue by openaudible** [r15ch13/audible-converter#7]
Wondering if you know of a mac os binary of rcrack. Hoping to bundle something like it into our new audible manager app. Thanks in advance for any pointers.

**Comment by openaudible** [comment]
Sorry found the full source on inaudible-ng and it compiled fine for mac.
- Max

**Comment by PythonicNinja** [comment]
indeed builds on m1 using https://github.com/inAudible-NG/RainbowCrack-NG

```bash
$ git clone git@github.com:inAudible-NG/RainbowCrack-NG.git
$ cd RainbowCrack-NG/src
$ c++ -L/usr/local/lib -L/opt/homebrew/Cellar/openssl@3/3.1.3/lib Public.o ChainWalkContext.o HashAlgorithm.o HashRoutine.o HashSet.o MemoryPool.o ChainWalkSet.o CrackEngine.o RainbowCrack.o -lssl -lcrypto -o rcrack
```

output:
```bash
$ file rcrack
rcrack: Mach-O 64-bit executable arm64
```
